[package]
name = "highhz-mouse-fix"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
env_logger = "0.11.5"
libc = "0.2.159"
linux-input = "0.1"
log = "0.4.22"
parking_lot = "0.12.3"
udev = "0.9.0"
